### ISSUE TITLE
No module named 'tfts.dataset'

### ISSUE THREAD

**Issue by XionZi** [LongxingTan/Time-series-prediction#10]
## ❔Question
您好，我在执行`run_train.py`文件时遇到了这个错误`No module named 'tfts.dataset'`，我发现`tfts`的`init`文件中`import`了`.dataset`，但是`tfts`下没有`dataset`这个文件夹，请问这是什么原因，是缺失了文件吗？

**Comment by LongxingTan** [comment]
@XionZi 
你可以先把`init`中的`from .dataset import *`注释掉即可，不影响。dataset本来是准备后面更新的feature，提交时文件夹还是空的所以没有传上来导致import报错了

**Comment by XionZi** [comment]
明白了，感谢！
