### ISSUE TITLE
Error in seq2seq model

### ISSUE THREAD

**Issue by helonin** [LongxingTan/Time-series-prediction#12]
## ❔Question
使用seq2seq模型时，报错 “TypeError: tf__call() missing 1 required positional argument: 'v'”
经查，是seq2seq.py的第96行：attention_feature = self.attention(tf.expand_dims(prev_state[-1], 1), encoder_output)
引用layers.attention_layer的attention函数时缺少参数 v
麻烦大侠查看一下。

**Comment by karta282950** [comment]
去attention_layer.py，修改下Attention里面的q,k,v就可以了

**Comment by LoneFireBlossom** [comment]
> 去attention_layer.py，修改下Attention里面的q,k,v就可以了

请问应该怎么改这几个参数啊，看了一天也没看懂🥲

**Comment by karta282950** [comment]
` def call(self, q, v, k=None, mask=None):
        """
        use query and key generating an attention multiplier for value, multi_heads to repeat it
        Args:
            Query: batch * seq_q * fea
            Key: batch * seq_k * fea
            Value: batch * seq_v * fea
            mask: important to avoid the leaks
        Returns:
            output: batch * key_sequence * (units * num_heads)
        """
        if k is None:
            k = v
            
        q = self.dense_q(q)  # project the query/key/value to num_heads * units
        k = self.dense_k(k)
        v = self.dense_v(v)

        q_ = tf.concat(tf.split(q, self.num_heads, axis=2), axis=0)  # multi-heads transfer to
        k_ = tf.concat(tf.split(k, self.num_heads, axis=2), axis=0)
        v_ = tf.concat(tf.split(v, self.num_heads, axis=2), axis=0)

        score = tf.linalg.matmul(q_, k_, transpose_b=True)  # => (batch*heads) * seq_q * seq_k
        score /= tf.cast(tf.shape(q_)[-1], tf.float32) ** 0.5

        if mask is not None:
            score = score * tf.cast(mask, tf.float32)

        score = tf.nn.softmax(score)
        score = self.dropout(score)

        outputs = tf.linalg.matmul(score, v_)  # (batch*heads) * seq_q * units
        outputs = tf.concat(tf.split(outputs, self.num_heads, axis=0), axis=2)
        return outputs`

**Comment by LoneFireBlossom** [comment]
> tfts/layers/attention_layer.py的Attention模块修改。
> 
> def call(self, q, v, k=None, mask=None): if k is None: k = v q = self.dense_q(q) k = self.dense_k(k) v = self.dense_v(v) q_ = tf.concat(tf.split(q, self.num_heads, axis=2), axis=0) # multi-heads transfer to k_ = tf.concat(tf.split(k, self.num_heads, axis=2), axis=0) v_ = tf.concat(tf.split(v, self.num_heads, axis=2), axis=0) score = tf.linalg.matmul(q_, k_, transpose_b=True) # => (batch_heads) * seq_q * seq_k score /= tf.cast(tf.shape(q_)[-1], tf.float32) ** 0.5 if mask is not None: score = score * tf.cast(mask, tf.float32) score = tf.nn.softmax(score) score = self.dropout(score) outputs = tf.linalg.matmul(score, v_) # (batch_heads) * seq_q * units outputs = tf.concat(tf.split(outputs, self.num_heads, axis=0), axis=2) return outputs

感谢，应该就是把参数改一下，然后前面加一个if：

```
def call(self, q, v, k=None, mask=None):
    if k is None:
        k = v
	＃下面都不用改
    q = self.dense_q(q)  # project the query/key/value to num_heads * units
    k = self.dense_k(k)
    v = self.dense_v(v)
```

**Comment by karta282950** [comment]
是的, 我是参考tensorflow官网改的, 你可以看下：https://github.com/keras-team/keras/blob/v2.8.0/keras/layers/dense_attention.py#L221-L356
另外楼主如果有解决到问题, 麻烦把issue设为closed~
