### ISSUE TITLE
如何在只有一张表的情况下选取验证集？

### ISSUE THREAD

**Issue by forestbat** [LongxingTan/Time-series-prediction#25]
首先感谢作者的工作。
我有这样的一个CSV数据集：
```
TM,Z
1,97.92
2,97.92
3,97.92
4,97.93
5,97.93
6,97.93
7,97.93
8,97.94
……
```
现在我准备用seq2seq预测以后的Z值，步骤如下：
```
test_df = pd.read_csv('my_table.csv')
X_train, X_test, Y_train, Y_test = train_test_split(test_df.index, stcd_df['Z'], test_size=0.25)
train_length = len(X_train)
predict_length = len(X_test)
model = AutoModel('seq2seq', predict_length)
trainer = KerasTrainer(model)
X_train_dim = np.expand_dims(X_train.values, axis=(0, -1))
X_test_dim = np.expand_dims(X_test.values, axis=(0, -1))
Y_train_dim = np.expand_dims(Y_train.values, axis=(0, -1))
Y_test_dim = np.expand_dims(X_test.values, axis=(0, -1))
trainer.train(train_dataset=(X_train_dim, Y_train_dim), valid_dataset=?)
```
如果将`valid_dataset`设置为None会报错（虽然注释里写着valid_dataset可以为None），但如果将`valid_dataset`设置为`(X_train_dim, Y_train_dim)`或者`(X_test_dim, Y_test_dim)`，都会报错：
`Incompatible shapes: [1,5081,1] vs. [1,15240,1] [Op:SquaredDifference]`（在本例中，train_length=15240，predict_length=5081）
请问我该怎么填`valid_dataset`？

**Comment by LongxingTan** [comment]
@forestbat 你好，

之前0.0.4版本里确实需要有一个valid_data，我跑了下如果像你说的把train放在valid应该是没问题的.
```
trainer.train(train, train)
```

我在这里简单试了一下：[https://aistudio.baidu.com/aistudio/projectdetail/5177231](https://aistudio.baidu.com/aistudio/projectdetail/5177231)

你也可以试试 安装最新的tfts==0.0.5，valid可以不填。
不过，我看你的训练和预测序列都这么长，感觉效果可能一言难尽哈，不知道这个数据的模式怎么样

**Comment by forestbat** [comment]
@LongxingTan 谢谢回复，我下了tfts 0.0.5重新跑了一下，发现报错是这样：
```
y_true = <tf.Tensor: shape=(1, 15240, 1), dtype=float32, numpy=……）
y_pred = <tf.Tensor: shape=(1, 5081, 1), dtype=float32, numpy=……）
Incompatible shapes: [1,5081,1] vs. [1,15240,1] [Op:SquaredDifference]
```
显然，`(1, 15240, 1)`是`X_train_dim`和`Y_train_dim`的维度，而(1, 5081, 1)是`X_test_dim`和`Y_test_dim`的维度，同时也是`predict_length`，问题出在这里。
而在你用`get_sine`方法生成的数据集中，x_train维度是(90, 24, 1), y_train维度是(90, 8, 1), x_valid维度是(10, 24, 1), y_valid维度是 (10, 8, 1)，也就是说x/y_train.shape[1]要等于x/y_valid.shape[1]才行。
——————————————————————————————————
关于数据模式，这是个时间和水位关系表，原始格式是这样：
```
TM,Z
2020-05-09 04:00:00,97.92
2020-05-09 05:00:00,97.92
2020-05-09 06:00:00,97.92
2020-05-09 07:00:00,97.93
2020-05-09 08:00:00,97.93
2020-05-09 09:00:00,97.93
2020-05-09 10:00:00,97.93
2020-05-09 11:00:00,97.93
2020-05-09 12:00:00,97.93
2020-05-09 13:00:00,97.93
```
测试时为了方便，会将表格重采样成1h步长并对`Z`线性插值，再用`Z`序列做预测，长度可以自定，主要考察预测值和真实值的R²和RMSE。

**Comment by LongxingTan** [comment]
@forestbat 

是的，
这里的第二维是序列长度。假定我要用15240个历史序列，预测未来的5081个长度。那么训练和验证、测试的历史序列都需要是15240；训练、验证和测试的输出序列则都是5081

你可以多试试，看你前几个数据的变化倒是不大

**Comment by forestbat** [comment]
我试了两种数据组织方法：

1. 按照[这里](https://github.com/lkulowski/LSTM_encoder_decoder)提到的方法，将Z列数据组织成训练集和测试集，Xtrain/Ytrain维度为(n_sample_train, 72, 1)，Xtest/Ytest维度为(n_sample_test, 72, 1)；
2. 取特定时间点之前72个时间点(用作X)和之后72个时间点(用作Y)的Z值序列，然后将多个序列拼成训练集和测试集，Xtrain/Ytrain/Xtest/Ytest维度大小同上。

然后基于此代码开始训练与评估：
```
with tf.device('/gpu:0'):
        model = AutoModel('seq2seq', out)
        trainer = KerasTrainer(model)
        trainer.train(train_dataset=(X_train, Y_train), n_epochs=50)
        pred = trainer.predict(X_test)
    for sample in range(0, Y_test.shape[0] // 10):
        # 针对n_sample中每个序列分别判断RMSE和R²
        rmse = sqrt(metrics.mean_squared_error(Y_test[sample, :, :], pred[sample, :, :]))
        r2 = metrics.r2_score(Y_test[sample, :, :], pred[sample, :, :])
        print(rmse, r2, sep=',')
    trainer.plot(history=X_test, true=Y_test, pred=pred)
    plt.show()
```
结果输出的一批R²和RMSE都不好(R²负值占绝大多数)，有办法改进吗？

**Comment by LongxingTan** [comment]
@forestbat 

对结果比较有显著影响的，比如
- 对这列数据进行不同的标准化或者变换函数
- 如果周期性较强，那预测结果时，预测最后一步人工加上对应的周期
- 异常点是不是太明显等

**Comment by forestbat** [comment]
作者晚上好，因为一些其他事情没有及时回复，现在对整张表用`sklearn.StandardScaler`统一归一化，再拆分成训练集和测试集，将预测值用测试集归一化器逆归一化，R²和RMSE效果好了一些，尤其是R²出现了一定数量正值：
```
RMSE                R²
0.08453548571252031,-0.4927430812400264
0.07525082823617335,-0.2611482807611303
0.0654720718395941,-0.01665754327936564
0.06744408581981853,-0.15973211759265493
0.04199690210167954,0.5225568629720714
0.0288474858965037,0.7600075734788329
0.02886195226222785,0.7447052809029342
0.028612368663810624,0.7308216810032169
0.030191761324181755,0.6792922636535399
0.050338946335673214,0.06145113441491945
0.05967947334014888,-0.39943149449799376
0.08429349823184663,-1.9104268084811546
……
```
现在有几个问题：
1.即便是相同的参数，RNN-seq2seq的RMSE和R²结果也不稳定，如何配置使得测试结果固定下来，可被复现？
2.几次测试中，Loss值变化趋势大概如下：
```
Epoch 1/25
194/194 - 104s - loss: 0.1277 - 104s/epoch - 535ms/step
Epoch 2/25
194/194 - 88s - loss: 0.0178 - 88s/epoch - 456ms/step
Epoch 3/25
194/194 - 87s - loss: 0.0150 - 87s/epoch - 449ms/step
Epoch 4/25
194/194 - 87s - loss: 0.0140 - 87s/epoch - 447ms/step
Epoch 5/25
194/194 - 99s - loss: 0.0130 - 99s/epoch - 511ms/step
Epoch 6/25
194/194 - 89s - loss: 0.0138 - 89s/epoch - 460ms/step
Epoch 7/25
194/194 - 91s - loss: 0.0121 - 91s/epoch - 468ms/step
Epoch 8/25
194/194 - 106s - loss: 0.0120 - 106s/epoch - 545ms/step
Epoch 9/25
194/194 - 97s - loss: 0.0115 - 97s/epoch - 502ms/step
Epoch 10/25
194/194 - 91s - loss: 0.0153 - 91s/epoch - 470ms/step
Epoch 11/25
194/194 - 91s - loss: 0.0146 - 91s/epoch - 467ms/step
Epoch 12/25
194/194 - 92s - loss: 0.0127 - 92s/epoch - 474ms/step
```
可以看出loss值从一开始就很低，下降过程也不太稳定，这种变化是否正常，如果有误，又该怎么改进？
3.“如果周期性较强，那预测结果时，预测最后一步人工加上对应的周期”这步怎么做，没太看明白。
已知数据没有太多异常点，总体正常。

**Comment by LongxingTan** [comment]
1 训练的时候固定一下seed
```
def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    tf.random.set_seed(seed)
```

2. 归一化以后一些参数需要重新调整。比如学习率需要小一点之类，学习率很大的时候几下就学完了，可能就围绕着某个极值晃悠了

**Comment by forestbat** [comment]
多谢解答！
custom_model_params有哪些参数可供指定，有文档吗？在库里直接搜只搜到一个
`custom_model_params = {"rnn_size": 128, "dense_size": 128}`。

**Comment by LongxingTan** [comment]
以rnn模型为例，

查看的方法：
```
from tfts import AutoConfig, AutoModel
AutoConfig('rnn').print_config()
```

修改的时候，
```
model = AutoModel('rnn', predict_length=1, custom_model_params={...})
```

不过我记得目前测试还没有覆盖到这种比较细的参数修改哈，可能有的会有错
