### ISSUE TITLE
google-colab require pandas==2.0.3 but tfts requires pandas less than 2.0.0

### ISSUE THREAD

**Issue by gitgud** [LongxingTan/Time-series-prediction#51]
- TFTS version: 0.0.10

google-colab require pandas==2.0.3 but tfts requires pandas less than 2.0.0.

message from google colab output: 
google-colab 1.0.0 requires pandas==2.0.3, but you have pandas 2.2.2 which is incompatible.
tfts 0.0.10 requires pandas<2.0.0,>=1.2.0, but you have pandas 2.2.2 which is incompatible.

**Comment by LongxingTan** [comment]
@gitgud 
Thanks for the reminding, you can try to install tfts==0.0.11

**Comment by gitgud** [comment]
Awesome thanks!
