### ISSUE TITLE
No such file or directory: '../models\\scaler.pkl'

### ISSUE THREAD

**Issue by MichaelRinger** [LongxingTan/Time-series-prediction#7]
Hey,

this error came up when i start to train any model. I also tried it on my other pc, its probably a configuration problem.
Thanks for help

train:
python run_train.py --use_model seq2seq

error:
FileNotFoundError: [Errno 2] No such file or directory: '../models\\scaler.pkl'

**Comment by LongxingTan** [comment]
> Hey,
> 
> this error came up when i start to train any model. I also tried it on my other pc, its probably a configuration problem.
> Thanks for help
> 
> train:
> python run_train.py --use_model seq2seq
> 
> error:
> FileNotFoundError: [Errno 2] No such file or directory: '../models\scaler.pkl'

Thanks for the message.
After I update some code, the model_dir has been changed to '../weights\scaler.pkl'.
I will update soon.


in /examples/feature/norm_feature.py line 13
```
def __call__(self, x, mode='train', model_dir='../weights', name='scaler'):
```

**Comment by YakubFahimLuckyarno** [comment]
Hi, 

I already tried to change the directory into '../weights\scaler.pkl', but when I executed it through Python in terminal, I kept getting a message : 

FileNotFoundError: [Errno 2] No such file or directory: '../models/scaler.pkl'

Is there anything related to the pycache? Should I delete it in order to generate new cache?

Thank you very much

**Comment by LongxingTan** [comment]
@YakubFahimLuckyarno 
sorry i missed to mention another directory change.

in /example/data/read_data.py line 102
```
def get_examples(self, data_dir, sample=1, start_date=None, plot=False, model_dir='../weights'):
```

**Comment by YakubFahimLuckyarno** [comment]
> @YakubFahimLuckyarno
> sorry i missed to mention another directory change.
> 
> in /example/data/read_data.py line 102
> 
> ```
> def get_examples(self, data_dir, sample=1, start_date=None, plot=False, model_dir='../weights'):
> ```

Hi, 

thank you very much for you help. It is now working. 
Another question, if I want to use GAN, in the deepts/model.py, just add the script to call GAN, isn't it?

Thank you very much

**Comment by LongxingTan** [comment]
> > @YakubFahimLuckyarno
> > sorry i missed to mention another directory change.
> > in /example/data/read_data.py line 102
> > ```
> > def get_examples(self, data_dir, sample=1, start_date=None, plot=False, model_dir='../weights'):
> > ```
> 
> Hi,
> 
> thank you very much for you help. It is now working.
> Another question, if I want to use GAN, in the deepts/model.py, just add the script to call GAN, isn't it?
> 
> Thank you very much

After some reconstruction, I haven't test if GAN works or not now.
I guess I need some time to modify it to let it work again

**Comment by YakubFahimLuckyarno** [comment]
> > > @YakubFahimLuckyarno
> > > sorry i missed to mention another directory change.
> > > in /example/data/read_data.py line 102
> > > ```
> > > def get_examples(self, data_dir, sample=1, start_date=None, plot=False, model_dir='../weights'):
> > > ```
> > 
> > 
> > Hi,
> > thank you very much for you help. It is now working.
> > Another question, if I want to use GAN, in the deepts/model.py, just add the script to call GAN, isn't it?
> > Thank you very much
> 
> After some reconstruction, I haven't test if GAN works or not now.
> I guess I need some time to modify it to let it work again

Okay. I also tried to execute the run_train.py for model unet and nbeats. There were errors in both algorithm. In the model.py, you also give notes that the model used are seq2seq, wavenet, and transformer. Is it possible to execute the run_train.py with unet and nbeats?
